// Generated stable class-name contract shared by every complete theme.
const freeze = (value) => Object.freeze(value);

export const albumsPageStyles = freeze({
  "card": "pm-albums-page-card",
  "cardBody": "pm-albums-page-card-body",
  "cardTitle": "pm-albums-page-card-title",
  "centeredState": "pm-albums-page-centered-state",
  "cover": "pm-albums-page-cover",
  "coverImage": "pm-albums-page-cover-image",
  "coverStatus": "pm-albums-page-cover-status",
  "createCard": "pm-albums-page-create-card",
  "createHint": "pm-albums-page-create-hint",
  "createIcon": "pm-albums-page-create-icon",
  "createTitle": "pm-albums-page-create-title",
  "description": "pm-albums-page-description",
  "emptyIcon": "pm-albums-page-empty-icon",
  "errorIcon": "pm-albums-page-error-icon",
  "grid": "pm-albums-page-grid",
  "page": "pm-albums-page-page",
  "photoCount": "pm-albums-page-photo-count",
  "primaryButton": "pm-albums-page-primary-button",
  "secondaryButton": "pm-albums-page-secondary-button",
  "spinner": "pm-albums-page-spinner",
  "srOnly": "pm-albums-page-sr-only",
  "stateSpinner": "pm-albums-page-state-spinner",
});

export const createAlbumDialogStyles = freeze({
  "actions": "pm-create-album-dialog-actions",
  "backdrop": "pm-create-album-dialog-backdrop",
  "cancelButton": "pm-create-album-dialog-cancel-button",
  "closeButton": "pm-create-album-dialog-close-button",
  "dialog": "pm-create-album-dialog-dialog",
  "error": "pm-create-album-dialog-error",
  "field": "pm-create-album-dialog-field",
  "form": "pm-create-album-dialog-form",
  "header": "pm-create-album-dialog-header",
  "heading": "pm-create-album-dialog-heading",
  "sharedDialog": "pm-create-album-dialog-shared-dialog",
  "spinner": "pm-create-album-dialog-spinner",
  "submitButton": "pm-create-album-dialog-submit-button",
  "titleIcon": "pm-create-album-dialog-title-icon",
});

export const importWizardStyles = freeze({
  "body": "pm-import-wizard-body",
  "brushActive": "pm-import-wizard-brush-active",
  "closeButton": "pm-import-wizard-close-button",
  "configError": "pm-import-wizard-config-error",
  "duplicateNotice": "pm-import-wizard-duplicate-notice",
  "emptyState": "pm-import-wizard-empty-state",
  "header": "pm-import-wizard-header",
  "headerIcon": "pm-import-wizard-header-icon",
  "inlineError": "pm-import-wizard-inline-error",
  "overlay": "pm-import-wizard-overlay",
  "previewContent": "pm-import-wizard-preview-content",
  "previewPanel": "pm-import-wizard-preview-panel",
  "previewScroller": "pm-import-wizard-preview-scroller",
  "sentinel": "pm-import-wizard-sentinel",
  "spinner": "pm-import-wizard-spinner",
  "wizard": "pm-import-wizard-wizard",
});

export const mapTemporaryAlbumStyles = freeze({
  "browser": "pm-map-temporary-album-browser",
  "header": "pm-map-temporary-album-header",
  "heading": "pm-map-temporary-album-heading",
  "icon": "pm-map-temporary-album-icon",
  "page": "pm-map-temporary-album-page",
});

export const mapViewStyles = freeze({
  "centeredState": "pm-map-view-centered-state",
  "clusterCount": "pm-map-view-cluster-count",
  "clusterMarker": "pm-map-view-cluster-marker",
  "clusterShell": "pm-map-view-cluster-shell",
  "clusterVisual": "pm-map-view-cluster-visual",
  "map": "pm-map-view-map",
  "marker": "pm-map-view-marker",
  "markerCount": "pm-map-view-marker-count",
  "markerDot": "pm-map-view-marker-dot",
  "markerFocused": "pm-map-view-marker-focused",
  "markerShell": "pm-map-view-marker-shell",
  "markerThumbnail": "pm-map-view-marker-thumbnail",
  "markerThumbnailPlaceholder": "pm-map-view-marker-thumbnail-placeholder",
  "markerVisual": "pm-map-view-marker-visual",
  "networkWarning": "pm-map-view-network-warning",
  "page": "pm-map-view-page",
  "summary": "pm-map-view-summary",
});

export const settingsPageStyles = freeze({
  "aboutDetails": "pm-settings-page-about-details",
  "aboutHeader": "pm-settings-page-about-header",
  "card": "pm-settings-page-card",
  "cardHeader": "pm-settings-page-card-header",
  "cardStack": "pm-settings-page-card-stack",
  "content": "pm-settings-page-content",
  "dangerRow": "pm-settings-page-danger-row",
  "languageSelect": "pm-settings-page-language-select",
  "themeSelect": "pm-settings-page-theme-select",
  "limitControl": "pm-settings-page-limit-control",
  "loading": "pm-settings-page-loading",
  "mono": "pm-settings-page-mono",
  "operationStatus": "pm-settings-page-operation-status",
  "page": "pm-settings-page-page",
  "pathControl": "pm-settings-page-path-control",
  "progress": "pm-settings-page-progress",
  "refreshButton": "pm-settings-page-refresh-button",
  "scaleControl": "pm-settings-page-scale-control",
  "scaleReset": "pm-settings-page-scale-reset",
  "scaleValue": "pm-settings-page-scale-value",
  "savedBadge": "pm-settings-page-saved-badge",
  "sectionActive": "pm-settings-page-section-active",
  "sectionNav": "pm-settings-page-section-nav",
  "segmentActive": "pm-settings-page-segment-active",
  "segmented": "pm-settings-page-segmented",
  "settingControl": "pm-settings-page-setting-control",
  "settingCopy": "pm-settings-page-setting-copy",
  "settingIcon": "pm-settings-page-setting-icon",
  "settingRow": "pm-settings-page-setting-row",
  "shell": "pm-settings-page-shell",
  "spin": "pm-settings-page-spin",
  "statCard": "pm-settings-page-stat-card",
  "statIcon": "pm-settings-page-stat-icon",
  "statsGrid": "pm-settings-page-stats-grid",
  "switch": "pm-settings-page-switch",
  "switchOn": "pm-settings-page-switch-on",
  "warning": "pm-settings-page-warning",
  "workspaceDetails": "pm-settings-page-workspace-details",
});

export const timelineGridStyles = freeze({
  "compareAlbum": "pm-timeline-grid-compare-album",
  "browserPane": "pm-timeline-grid-browser-pane",
  "compareBrowserDetail": "pm-timeline-grid-compare-browser-detail",
  "compareBrowser": "pm-timeline-grid-compare-browser",
  "compareExit": "pm-timeline-grid-compare-exit",
  "compareLayout": "pm-timeline-grid-compare-layout",
  "comparePreview": "pm-timeline-grid-compare-preview",
  "content": "pm-timeline-grid-content",
  "inlineError": "pm-timeline-grid-inline-error",
  "scrollArea": "pm-timeline-grid-scroll-area",
  "spinner": "pm-timeline-grid-spinner",
  "state": "pm-timeline-grid-state",
  "viewport": "pm-timeline-grid-viewport",
});

export const workspaceSelectorStyles = freeze({
  "actionError": "pm-workspace-selector-action-error",
  "card": "pm-workspace-selector-card",
  "deleteButton": "pm-workspace-selector-delete-button",
  "eyebrow": "pm-workspace-selector-eyebrow",
  "form": "pm-workspace-selector-form",
  "formActions": "pm-workspace-selector-form-actions",
  "header": "pm-workspace-selector-header",
  "input": "pm-workspace-selector-input",
  "lastOpened": "pm-workspace-selector-last-opened",
  "listStatus": "pm-workspace-selector-list-status",
  "logo": "pm-workspace-selector-logo",
  "pathControl": "pm-workspace-selector-path-control",
  "recentIcon": "pm-workspace-selector-recent-icon",
  "recentInfo": "pm-workspace-selector-recent-info",
  "recentItem": "pm-workspace-selector-recent-item",
  "recentList": "pm-workspace-selector-recent-list",
  "recentOpen": "pm-workspace-selector-recent-open",
  "recents": "pm-workspace-selector-recents",
  "screen": "pm-workspace-selector-screen",
  "sectionHeading": "pm-workspace-selector-section-heading",
});

export const importControlsStyles = freeze({
  "activeBrush": "pm-import-controls-active-brush",
  "activeChoice": "pm-import-controls-active-choice",
  "brushChoice": "pm-import-controls-brush-choice",
  "brushList": "pm-import-controls-brush-list",
  "brushName": "pm-import-controls-brush-name",
  "choiceList": "pm-import-controls-choice-list",
  "colorDot": "pm-import-controls-color-dot",
  "compactHint": "pm-import-controls-compact-hint",
  "configurationContent": "pm-import-controls-configuration-content",
  "configurationHeader": "pm-import-controls-configuration-header",
  "configurationOpen": "pm-import-controls-configuration-open",
  "configurationPanel": "pm-import-controls-configuration-panel",
  "configurationRoot": "pm-import-controls-configuration-root",
  "configurationScrim": "pm-import-controls-configuration-scrim",
  "configurationTrigger": "pm-import-controls-configuration-trigger",
  "confirmBar": "pm-import-controls-confirm-bar",
  "confirmShortcuts": "pm-import-controls-confirm-shortcuts",
  "confirmStats": "pm-import-controls-confirm-stats",
  "errorStatus": "pm-import-controls-error-status",
  "field": "pm-import-controls-field",
  "filterButtons": "pm-import-controls-filter-buttons",
  "growingSection": "pm-import-controls-growing-section",
  "helpText": "pm-import-controls-help-text",
  "iconTextButton": "pm-import-controls-icon-text-button",
  "importButton": "pm-import-controls-import-button",
  "inputActionRow": "pm-import-controls-input-action-row",
  "locationStatus": "pm-import-controls-location-status",
  "location_error": "pm-import-controls-location-error",
  "location_ready": "pm-import-controls-location-ready",
  "mutedStatus": "pm-import-controls-muted-status",
  "pressedButton": "pm-import-controls-pressed-button",
  "previewControls": "pm-import-controls-preview-controls",
  "previewStats": "pm-import-controls-preview-stats",
  "previewToolbar": "pm-import-controls-preview-toolbar",
  "progressBackdrop": "pm-import-controls-progress-backdrop",
  "progressBody": "pm-import-controls-progress-body",
  "progressCard": "pm-import-controls-progress-card",
  "progressHeading": "pm-import-controls-progress-heading",
  "progressIcon": "pm-import-controls-progress-icon",
  "progressTrack": "pm-import-controls-progress-track",
  "scanStatus": "pm-import-controls-scan-status",
  "section": "pm-import-controls-section",
  "sectionHeading": "pm-import-controls-section-heading",
  "sectionHeadingRow": "pm-import-controls-section-heading-row",
  "sectionIcon": "pm-import-controls-section-icon",
  "spinner": "pm-import-controls-spinner",
  "subheadingRow": "pm-import-controls-subheading-row",
  "switchRow": "pm-import-controls-switch-row",
  "textButton": "pm-import-controls-text-button",
});

export const importViewsStyles = freeze({
  "activeFilm": "pm-import-views-active-film",
  "albumOverlay": "pm-import-views-album-overlay",
  "alreadyImported": "pm-import-views-already-imported",
  "cardName": "pm-import-views-card-name",
  "empty": "pm-import-views-empty",
  "film": "pm-import-views-film",
  "filmStatus": "pm-import-views-film-status",
  "filmstrip": "pm-import-views-filmstrip",
  "focused": "pm-import-views-focused",
  "gallery": "pm-import-views-gallery",
  "galleryCaption": "pm-import-views-gallery-caption",
  "galleryMedia": "pm-import-views-gallery-media",
  "galleryNav": "pm-import-views-gallery-nav",
  "galleryPreviewLoading": "pm-import-views-gallery-preview-loading",
  "galleryStage": "pm-import-views-gallery-stage",
  "importedBadge": "pm-import-views-imported-badge",
  "importedFilmStatus": "pm-import-views-imported-film-status",
  "importedText": "pm-import-views-imported-text",
  "list": "pm-import-views-list",
  "listGrid": "pm-import-views-list-grid",
  "listHeader": "pm-import-views-list-header",
  "listName": "pm-import-views-list-name",
  "listRow": "pm-import-views-list-row",
  "listScroller": "pm-import-views-list-scroller",
  "listStatus": "pm-import-views-list-status",
  "listThumb": "pm-import-views-list-thumb",
  "masonry": "pm-import-views-masonry",
  "masonryCard": "pm-import-views-masonry-card",
  "masonryMedia": "pm-import-views-masonry-media",
  "next": "pm-import-views-next",
  "previous": "pm-import-views-previous",
  "rawBadge": "pm-import-views-raw-badge",
  "selected": "pm-import-views-selected",
  "skippedText": "pm-import-views-skipped-text",
  "thumbnail": "pm-import-views-thumbnail",
  "thumbnail__PM_GLOBAL_0__": "pm-import-views-thumbnail--pm-global-0--",
});

export const lightboxStyles = freeze({
  "canvas": "pm-lightbox-canvas",
  "canvasRegion": "pm-lightbox-canvas-region",
  "clearColorItem": "pm-lightbox-clear-color-item",
  "colorMenu": "pm-lightbox-color-menu",
  "colorMenuItem": "pm-lightbox-color-menu-item",
  "colorMenuPopup": "pm-lightbox-color-menu-popup",
  "colorMenuSeparator": "pm-lightbox-color-menu-separator",
  "colorSwatch": "pm-lightbox-color-swatch",
  "detailsDock": "pm-lightbox-details-dock",
  "divider": "pm-lightbox-divider",
  "dragging": "pm-lightbox-dragging",
  "fileGrid": "pm-lightbox-file-grid",
  "image": "pm-lightbox-image",
  "imageLoading": "pm-lightbox-image-loading",
  "importOverlay": "pm-lightbox-import-overlay",
  "infoPanel": "pm-lightbox-info-panel",
  "infoSection": "pm-lightbox-info-section",
  "loading": "pm-lightbox-loading",
  "locationCoordinates": "pm-lightbox-location-coordinates",
  "main": "pm-lightbox-main",
  "mapButton": "pm-lightbox-map-button",
  "metadataGrid": "pm-lightbox-metadata-grid",
  "metadataItem": "pm-lightbox-metadata-item",
  "metadataWide": "pm-lightbox-metadata-wide",
  "mono": "pm-lightbox-mono",
  "navButton": "pm-lightbox-nav-button",
  "next": "pm-lightbox-next",
  "overlay": "pm-lightbox-overlay",
  "previous": "pm-lightbox-previous",
  "rating": "pm-lightbox-rating",
  "star": "pm-lightbox-star",
  "starActive": "pm-lightbox-star-active",
  "tagChip": "pm-lightbox-tag-chip",
  "tagForm": "pm-lightbox-tag-form",
  "tagInputRow": "pm-lightbox-tag-input-row",
  "tagList": "pm-lightbox-tag-list",
  "thumbnail": "pm-lightbox-thumbnail",
  "toolbar": "pm-lightbox-toolbar",
  "toolbarGroup": "pm-lightbox-toolbar-group",
  "topActions": "pm-lightbox-top-actions",
  "visible": "pm-lightbox-visible",
  "zoomValue": "pm-lightbox-zoom-value",
  "zoomed": "pm-lightbox-zoomed",
});

export const viewSwitcherStyles = freeze({
  "active": "pm-view-switcher-active",
  "switcher": "pm-view-switcher-switcher",
});

export const batchActionBarStyles = freeze({
  "actionButton": "pm-batch-action-bar-action-button",
  "actions": "pm-batch-action-bar-actions",
  "active": "pm-batch-action-bar-active",
  "bar": "pm-batch-action-bar-bar",
  "danger": "pm-batch-action-bar-danger",
  "dangerSubtle": "pm-batch-action-bar-danger-subtle",
  "separator": "pm-batch-action-bar-separator",
  "success": "pm-batch-action-bar-success",
  "summary": "pm-batch-action-bar-summary",
});

export const moveAlbumDialogStyles = freeze({
  "albumIcon": "pm-move-album-dialog-album-icon",
  "albumList": "pm-move-album-dialog-album-list",
  "albumName": "pm-move-album-dialog-album-name",
  "backdrop": "pm-move-album-dialog-backdrop",
  "body": "pm-move-album-dialog-body",
  "dialog": "pm-move-album-dialog-dialog",
  "empty": "pm-move-album-dialog-empty",
  "error": "pm-move-album-dialog-error",
  "header": "pm-move-album-dialog-header",
  "headerIcon": "pm-move-album-dialog-header-icon",
  "sharedDialog": "pm-move-album-dialog-shared-dialog",
  "spinner": "pm-move-album-dialog-spinner",
});

export const photoInspectorStyles = freeze({
  "activeStar": "pm-photo-inspector-active-star",
  "clearRating": "pm-photo-inspector-clear-rating",
  "content": "pm-photo-inspector-content",
  "detailRow": "pm-photo-inspector-detail-row",
  "details": "pm-photo-inspector-details",
  "emptyTags": "pm-photo-inspector-empty-tags",
  "header": "pm-photo-inspector-header",
  "headerIcon": "pm-photo-inspector-header-icon",
  "inspector": "pm-photo-inspector-inspector",
  "rating": "pm-photo-inspector-rating",
  "scrim": "pm-photo-inspector-scrim",
  "section": "pm-photo-inspector-section",
  "sectionHeading": "pm-photo-inspector-section-heading",
  "tagChip": "pm-photo-inspector-tag-chip",
  "tagForm": "pm-photo-inspector-tag-form",
  "tagList": "pm-photo-inspector-tag-list",
  "visuallyHidden": "pm-photo-inspector-visually-hidden",
});

export const timelineToolbarStyles = freeze({
  "activeView": "pm-timeline-toolbar-active-view",
  "desktopFilters": "pm-timeline-toolbar-desktop-filters",
  "filterField": "pm-timeline-toolbar-filter-field",
  "filterFields": "pm-timeline-toolbar-filter-fields",
  "filterSelect": "pm-timeline-toolbar-filter-select",
  "filterSelectRoot": "pm-timeline-toolbar-filter-select-root",
  "mobileFilterBackdrop": "pm-timeline-toolbar-mobile-filter-backdrop",
  "mobileFilterButton": "pm-timeline-toolbar-mobile-filter-button",
  "mobileFilterPanel": "pm-timeline-toolbar-mobile-filter-panel",
  "searchField": "pm-timeline-toolbar-search-field",
  "toolbar": "pm-timeline-toolbar-toolbar",
  "viewSwitcher": "pm-timeline-toolbar-view-switcher",
  "visuallyHidden": "pm-timeline-toolbar-visually-hidden",
});

export const photoViewsStyles = freeze({
  "badge": "pm-photo-views-badge",
  "compareBase": "pm-photo-views-compare-base",
  "compareLabel": "pm-photo-views-compare-label",
  "favoriteBadge": "pm-photo-views-favorite-badge",
  "favoritePrefix": "pm-photo-views-favorite-prefix",
  "fileTypeBadge": "pm-photo-views-file-type-badge",
  "filename": "pm-photo-views-filename",
  "filmItem": "pm-photo-views-film-item",
  "listRow": "pm-photo-views-list-row",
  "overlay": "pm-photo-views-overlay",
  "photoItem": "pm-photo-views-photo-item",
  "rating": "pm-photo-views-rating",
});

export const globalDialogStyles = freeze({
  "accent": "pm-global-dialog-accent",
  "backdrop": "pm-global-dialog-backdrop",
  "body": "pm-global-dialog-body",
  "closeButton": "pm-global-dialog-close-button",
  "dialog": "pm-global-dialog-dialog",
  "footer": "pm-global-dialog-footer",
  "header": "pm-global-dialog-header",
  "heading": "pm-global-dialog-heading",
  "icon": "pm-global-dialog-icon",
  "inputField": "pm-global-dialog-input-field",
  "kicker": "pm-global-dialog-kicker",
  "message": "pm-global-dialog-message",
});

export const uiStyles = freeze({
  "button": "pm-ui-button",
  "buttonFullWidth": "pm-ui-button-full-width",
  "button_danger": "pm-ui-button-danger",
  "button_ghost": "pm-ui-button-ghost",
  "button_icon": "pm-ui-button-icon",
  "button_md": "pm-ui-button-md",
  "button_navigation": "pm-ui-button-navigation",
  "button_primary": "pm-ui-button-primary",
  "button_secondary": "pm-ui-button-secondary",
  "button_sm": "pm-ui-button-sm",
  "dialog": "pm-ui-dialog",
  "drawer": "pm-ui-drawer",
  "drawerOverlay": "pm-ui-drawer-overlay",
  "drawerScrim": "pm-ui-drawer-scrim",
  "drawer_left": "pm-ui-drawer-left",
  "drawer_right": "pm-ui-drawer-right",
  "emptyActions": "pm-ui-empty-actions",
  "emptyIcon": "pm-ui-empty-icon",
  "emptyState": "pm-ui-empty-state",
  "field": "pm-ui-field",
  "fieldError": "pm-ui-field-error",
  "fieldHint": "pm-ui-field-hint",
  "fieldLabel": "pm-ui-field-label",
  "overlay": "pm-ui-overlay",
  "overlayBody": "pm-ui-overlay-body",
  "overlayFooter": "pm-ui-overlay-footer",
  "overlayHeader": "pm-ui-overlay-header",
  "selectChevron": "pm-ui-select-chevron",
  "selectMenu": "pm-ui-select-menu",
  "selectOption": "pm-ui-select-option",
  "selectOptionHighlighted": "pm-ui-select-option-highlighted",
  "selectOptionSelected": "pm-ui-select-option-selected",
  "selectRoot": "pm-ui-select-root",
  "selectTrigger": "pm-ui-select-trigger",
  "spinner": "pm-ui-spinner",
  "spinnerWithLabel": "pm-ui-spinner-with-label",
  "spinnerWrap": "pm-ui-spinner-wrap",
  "spinner_lg": "pm-ui-spinner-lg",
  "spinner_md": "pm-ui-spinner-md",
  "spinner_sm": "pm-ui-spinner-sm",
});
